### ISSUE TITLE
NameError in logging in verbose mode

### ISSUE THREAD

**Issue by chrisjbillington** [sometoby/archlinux-checkrestart#3]
I get this NameError when running in verbose mode:

```
Traceback (most recent call last):
  File "/usr/bin/checkrestart", line 738, in <module>
    main()
  File "/usr/bin/checkrestart", line 231, in main
    print("[DEBUG] Running: %s" % ' '.join(dpkgQuery))
NameError: name 'dpkgQuery' is not defined
```

the variable should presumably be `pacmanQuery`

**Comment by sometoby** [comment]
Sorry, I'm not maintaining this anymore. You should probably be using [this](https://aur.archlinux.org/packages/needrestart) instead.
